// <auto-generated />
using ContactsWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsWebApplication.Migrations
{
    [DbContext(typeof(AccountDetailContext))]
    partial class AccountDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactsWebApplication.Models.AccountDetail", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nchar(9)");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("nchar(32)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nchar(32)");

                    b.HasKey("AccountID");

                    b.ToTable("AccountDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
